// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIQuim.Models;

#nullable disable

namespace SIQuim.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260328031506_InitialBaseline")]
    partial class InitialBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SIQuim.Models.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NumeroDeEmpleado")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Empleado__3214EC27180AE6A1");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("SIQuim.Models.Materiale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kanban")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PartNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("StdPack")
                        .HasColumnType("int");

                    b.Property<string>("Uom")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("UOM");

                    b.Property<string>("Vendor")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK__Material__3214EC276457C408");

                    b.ToTable("Materiales");
                });

            modelBuilder.Entity("SIQuim.Models.Registro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int")
                        .HasColumnName("MaterialID");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<int>("ResponsableEntrega")
                        .HasColumnType("int");

                    b.Property<int>("ResponsableReciba")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Registro__3214EC27595AEC86");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ResponsableEntrega");

                    b.HasIndex("ResponsableReciba");

                    b.ToTable("Registro", (string)null);
                });

            modelBuilder.Entity("SIQuim.Models.Stock", b =>
                {
                    b.Property<int>("StockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StockID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockId"));

                    b.Property<double>("Cantidad")
                        .HasColumnType("float");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int")
                        .HasColumnName("MaterialID");

                    b.Property<int>("UbicacionId")
                        .HasColumnType("int")
                        .HasColumnName("UbicacionID");

                    b.HasKey("StockId")
                        .HasName("PK__Stock__2C83A9E27F5DE0E3");

                    b.HasIndex("MaterialId");

                    b.HasIndex("UbicacionId");

                    b.ToTable("Stock", (string)null);
                });

            modelBuilder.Entity("SIQuim.Models.ToolCrib", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contenedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contenido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Costo")
                        .HasColumnType("float");

                    b.Property<DateOnly?>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<TimeOnly?>("Hora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("time")
                        .HasDefaultValueSql("(CONVERT([time],getdate()))");

                    b.Property<string>("Material")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Requisitor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unidad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__ToolCrib__3214EC2700DCEC7B");

                    b.ToTable("ToolCrib", (string)null);
                });

            modelBuilder.Entity("SIQuim.Models.Ubicacione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Ubicacio__10375DF57DE70632");

                    b.HasIndex(new[] { "Codigo" }, "UQ__Ubicacio__06370DAC038EC742")
                        .IsUnique();

                    b.ToTable("Ubicaciones");
                });

            modelBuilder.Entity("SIQuim.Models.Registro", b =>
                {
                    b.HasOne("SIQuim.Models.Materiale", "Material")
                        .WithMany("Registros")
                        .HasForeignKey("MaterialId")
                        .IsRequired()
                        .HasConstraintName("FK_Registro_Material");

                    b.HasOne("SIQuim.Models.Empleado", "ResponsableEntregaNavigation")
                        .WithMany("RegistroResponsableEntregaNavigations")
                        .HasForeignKey("ResponsableEntrega")
                        .IsRequired()
                        .HasConstraintName("FK_Registro_Entrega");

                    b.HasOne("SIQuim.Models.Empleado", "ResponsableRecibaNavigation")
                        .WithMany("RegistroResponsableRecibaNavigations")
                        .HasForeignKey("ResponsableReciba")
                        .IsRequired()
                        .HasConstraintName("FK_Registro_Reciba");

                    b.Navigation("Material");

                    b.Navigation("ResponsableEntregaNavigation");

                    b.Navigation("ResponsableRecibaNavigation");
                });

            modelBuilder.Entity("SIQuim.Models.Stock", b =>
                {
                    b.HasOne("SIQuim.Models.Materiale", "Material")
                        .WithMany("Stocks")
                        .HasForeignKey("MaterialId")
                        .IsRequired()
                        .HasConstraintName("FK_Stock_Materiales");

                    b.HasOne("SIQuim.Models.Ubicacione", "Ubicacion")
                        .WithMany("Stocks")
                        .HasForeignKey("UbicacionId")
                        .IsRequired()
                        .HasConstraintName("FK_Stock_Ubicaciones");

                    b.Navigation("Material");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("SIQuim.Models.Empleado", b =>
                {
                    b.Navigation("RegistroResponsableEntregaNavigations");

                    b.Navigation("RegistroResponsableRecibaNavigations");
                });

            modelBuilder.Entity("SIQuim.Models.Materiale", b =>
                {
                    b.Navigation("Registros");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("SIQuim.Models.Ubicacione", b =>
                {
                    b.Navigation("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
